### ISSUE TITLE
strings doesn't show on iOS

### ISSUE THREAD

**Issue by Romanososs** [jcraane/kmm-resources#14] opened 2022-08-30 07:55 UTC
I did everything by the book but instead of seeing my strings I get something like 'l.name.string' on iOS
KMMResourcesLocalization.kt have been generated for iosMain
My Gradle file
```
plugins {
    ...
    id("dev.jamiecraane.plugins.kmmresources") version "1.0.0-alpha10"
}

kotlin {
    android ()
    ios {
        binaries {
            framework {
                baseName = "shared"
            }
        }
    }
    val onPhone = System.getenv("SDK_NAME")?.startsWith("iphoneos") ?: false
    if (onPhone) {
        iosArm64("ios")
    } else {
        iosX64("ios")
    }
    sourceSets {
        ...
    }
}

android {
...
}

kmmResourcesConfig {
    androidApplicationId.set("app_name.app")
    packageName.set("app_name.shared.localization")
    defaultLanguage.set("en")
    input.set(File(project.projectDir.path, "generic.yaml"))
    output.set(project.projectDir)
    useDefaultTranslationIfNotInitialized.set(true)
}

val plutil = tasks["executePlutil"]

val generateLocalizations = tasks["generateLocalizations"]
tasks["preBuild"].dependsOn(generateLocalizations)

tasks {
    named("compileKotlinIosArm64") {
        dependsOn(plutil)
    }
    named("compileKotlinIosX64") {
        dependsOn(plutil)
    }
}

val packForXcode by tasks.creating(Sync::class) {
    group = "build"
    val mode = System.getenv("CONFIGURATION") ?: "DEBUG"
    val sdkName = System.getenv("SDK_NAME") ?: "iphonesimulator"
    val targetName = "ios" + if (sdkName.startsWith("iphoneos")) "Arm64" else "X64"
    val framework = kotlin.targets.getByName<KotlinNativeTarget>(targetName).binaries.getFramework(mode)
    inputs.property("mode", mode)
    dependsOn(framework.linkTask)
    val targetDir = File(buildDir, "xcode-frameworks")
    from({ framework.outputDirectory })
    into(targetDir)
    doLast {
        copy {
            from("${project.rootDir}/android-app/src/commonMain/resources/ios")
            into("${targetDir}/shared.framework")
        }
    }
}
tasks.getByName("build").dependsOn(packForXcode)
```

**Comment by StepIer** [comment] 2022-12-29 11:37
The same problem. Can author help resolve this issue, please?

**Comment by AyoPrez** [comment] 2023-03-20 19:25
@Romanososs  Did you find the problem or just gave up?

**Comment by jcraane** [comment] 2023-03-20 19:39
Soory for the late reply, rather busy. I will take a look this week.

**Comment by lammertw** [comment] 2023-03-20 19:43
One of the most common causes of this is forgetting to set the bundle from iOS:
```
let commonBundle = Bundle(for: L.self)
MultiLocalizationKt.localizationBundle = commonBundle
```

If that also doesn't work, please have a look if the shared iOS framework created by gradle contains localization files.

**Comment by AyoPrez** [comment] 2023-03-21 16:39
Hi. Thanks @lammertw for the suggestions. From the two points that you mention, about the first I'm sure I did it right:

This is how my Delegate looks like. The commented line was a trial, but I haven't noticed any difference between add the line in the AppDelegate file or in the init function.
```

@main
struct iOSApp: App {
    //@UIApplicationDelegateAdaptor(AppDelegate.self) var appDelegate
    
    init() {
        KMMResourcesLocalizationKt.localizationBundle = Bundle(for: L.self) // Bundle is initialized here
    }
    
	var body: some Scene {
		WindowGroup {
			LoginScreen()
		}
	}
}
```
The file is being created in the iOSMain directory of the shared module.

About the second suggestion, I'm not completely sure. 

My gradle task look like this:

```
val packForXcode by tasks.creating(Sync::class) {
    group = "build"
    val mode = System.getenv("CONFIGURATION") ?: "DEBUG"
    val sdkName = System.getenv("SDK_NAME") ?: "iphonesimulator"
    val targetName = "ios" + if (sdkName.startsWith("iphoneos")) "Arm64" else "X64"
    val framework = kotlin.targets.getByName<KotlinNativeTarget>(targetName).binaries.getFramework(mode)
    inputs.property("mode", mode)
    dependsOn(framework.linkTask)
    val targetDir = File(buildDir, "xcode-frameworks/$mode/$sdkName/shared.framework")
    println("targetDir = $targetDir")
    if (targetDir == null) {
        System.err.println("configuration.build.dir is not defined. Please pass this property from the XCode build.")
    } else {
        from({ framework.outputDirectory })
        into(targetDir)
    }

//    This is added to the packForXCode task. commonMain/resources/ios is the location of the gemerated Localizable.strings files.
    doLast {
        copy {
            from("${project.rootDir}/shared/src/commonMain/resources/ios")
            into("${project.buildDir}/xcode-frameworks/$mode/$sdkName/shared.framework")
        }
    }
}

tasks.getByName("build").dependsOn(packForXcode)
```
And this creates a folder in the shared module, inside the build directory, with the name “xcode-frameworks” with a file “shared.h”, where, among other stuff, I can see the texts that I have defined in the yalm file:

```
@interface SharedLGeneral (Extensions)
- (NSString *)appName __attribute__((swift_name("appName()")));
- (NSString *)cancel __attribute__((swift_name("cancel()")));
- (NSString *)no __attribute__((swift_name("no()")));
- (NSString *)ok __attribute__((swift_name("ok()")));
- (NSString *)today __attribute__((swift_name("today()")));
- (NSString *)yes __attribute__((swift_name("yes()")));
@end
```
I could not find a “.m” counterpart with the data.

Should I check further? Any specific directory?

**Comment by lammertw** [comment] 2023-03-22 15:47
You should be seeing folders for the languages that you've localized. In the following example the shared.framework has a en.lproj for English, es.lproj for Spanish and nl.lproj for Dutch. Inside all those folders should be a Localizable.strings with all the strings for that language.

<img width="701" alt="image" src="https://user-images.githubusercontent.com/826126/226960233-66443a96-0eb8-4faa-9e2b-653e7e348962.png">

So you're not seeing any of those?

**Comment by AyoPrez** [comment] 2023-03-22 15:59
Hi,
<img width="976" alt="Screenshot 2023-03-22 at 16 55 54 (2)" src="https://user-images.githubusercontent.com/4907089/226964101-d973bd92-6f9e-47db-a35a-c984fcc53af9.png">

Only the Headers and Modules folders (as you can appreciate in the image above).

Do you think it can be a problem in the configuration of the “packForXCode” task, or the problem is in the plugin itself?

**Comment by lammertw** [comment] 2023-03-22 16:08
I think the 'old' `packForXcode` might not be working well anymore. Can you try migrating to use `embedAndSignAppleFrameworkForXcode`. You should be able to follow https://blog.jetbrains.com/kotlin/2021/07/multiplatform-gradle-plugin-improved-for-connecting-kmm-modules/

**Comment by AyoPrez** [comment] 2023-03-22 16:43
Hi @lammertw,
thanks for the suggestion. I checked the article and what they mention there is set as it should in my project. It is a quite modern (it may have 3 or 4 months old) project, so it's using the ```embedAndSignAppleFrameworkForXcode``` already.

Maybe you or someone can confirm that everything looks good in this configuration (maybe the problem is here):

```
val packForXcode by tasks.creating(Sync::class) {
    group = "build"
    val mode = System.getenv("CONFIGURATION") ?: "DEBUG"
    val sdkName = System.getenv("SDK_NAME") ?: "iphonesimulator"
    val targetName = "ios" + if (sdkName.startsWith("iphoneos")) "Arm64" else "X64"
    val framework = kotlin.targets.getByName<KotlinNativeTarget>(targetName).binaries.getFramework(mode)
    println("---------Framework: ${framework.baseName} and Target: $targetName")
    inputs.property("mode", mode)
    dependsOn(framework.linkTask)
    val targetDir = File(buildDir, "xcode-frameworks/$mode/$sdkName/shared.framework")
    println("targetDir = $targetDir")
    if (targetDir == null) {
        System.err.println("configuration.build.dir is not defined. Please pass this property from the XCode build.")
    }
    from({ framework.outputDirectory })
    into(targetDir)

//    This is added to the packForXCode task. commonMain/resources/ios is the location of the gemerated Localizable.strings files.
    doLast {
        println("----Project dir: ${project.buildDir}")
        copy {
            from("${project.rootDir}/shared/src/commonMain/resources/ios")
            into("${project.buildDir}/xcode-frameworks/$mode/$sdkName/shared.framework")
        }
    }
}

tasks.getByName("build").dependsOn(packForXcode)
```

If for you works fine, it should be a problem in my side, and that configuration is, in my opinion, a candidate for the issue.

**Comment by lammertw** [comment] 2023-03-22 17:00
Right, I think I know the part you're missing (and we need to update documentation for this). You should remove the entire `packForXcode` since it's not being used anymore.

The copying part can instead be done like this:
```
tasks.withType<org.jetbrains.kotlin.gradle.tasks.KotlinNativeLink>().configureEach {
    if (outputKind != org.jetbrains.kotlin.konan.target.CompilerOutputKind.FRAMEWORK) return@configureEach
    val iosResources = project.layout.buildDirectory.dir("src/commonMain/resources/ios")

    doLast {
        iosResources.get().asFile.copyRecursively(outputFile.get(), true)
    }
}
```

Just replace the `packForXcode` with this and hopefully that will help.

**Comment by AyoPrez** [comment] 2023-03-22 17:28
Yes. That was it.
Thank you very much.
Now it works. Although, I had to do some changes to made it work in my case. 

```
tasks.withType<KotlinNativeLink>().configureEach {
    if (outputKind != CompilerOutputKind.FRAMEWORK) return@configureEach
    val iosResources: Provider<Directory> = project.layout.projectDirectory.dir(provider { "src/commonMain/resources/ios" })

    doLast {
        iosResources.get().asFile.copyRecursively(outputFile.get(), true)
    }
}
```

I had to replace the ```val iosReources = ....``` line, but after that change, I see the files in the build folder that you mentioned previously.

Please, update the documentation with this info. And I think we can close this issue.

**Comment by lammertw** [comment] 2023-03-22 17:30
Great to hear that it works now. I've already created a PR to update the documentation.
Please let us know if you encounter any other problem or if you'd like to share some feedback.

**Closed as completed by lammertw** 2023-03-22 17:30 UTC
